name: Trigger auto deployment for elo-assistente-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/elo-assistente-api-AutoDeployTrigger-c232385f-8abe-48fc-89a4-f8abf133ec82.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ELOASSISTENTEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ELOASSISTENTEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ELOASSISTENTEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.ELOASSISTENTEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ELOASSISTENTEAPI_REGISTRY_PASSWORD }}
          containerAppName: elo-assistente-api
          resourceGroup: rg-elo-assistente
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


